### ISSUE TITLE
提个PR，如果不是限定域名，可简化

### ISSUE THREAD

**Issue by xinggsf** [dupontjoy/customization#10]
如`^https?://.*hiphotos\.baidu\.com.*`
若不限定域名，可这样：`^http.*hiphotos\.baidu\.com.*`
但最好限定域名：`^https?://[^:/]+hiphotos\.baidu\.com.*`

**Comment by dupontjoy** [comment]
好的, 其实我的正则是半吊子, 只是勉强能用的水平
