### ISSUE TITLE
126图片盗链

### ISSUE THREAD

**Issue by zhouhuajdsh** [dupontjoy/customization#12]
对于http://imgout.ph.126.net/37404004/1116_12_18_01.jpg
需要头内容http://www.126.net

**Comment by dupontjoy** [comment]
这个图片能显示出来
麻烦提供下引用了此图片的那个网址

**Comment by zhouhuajdsh** [comment]
http://www.dayanzai.me/titanium-backup.html
这个网站的图片都是126的。我不加头内容就显示不出来

**Comment by dupontjoy** [comment]
奇怪, 我这里可以显示
我用的Nightly版, 可能不同Firefox版本效果有点不同
要不你自已改下吧
![34](https://user-images.githubusercontent.com/4965288/32879475-11626600-cae5-11e7-9616-66cf01af0088.jpg)

**Comment by zhouhuajdsh** [comment]
firefox确实没问题，但chrome系的不行。测试了极速和百分都必须加头内容才显示出来。
我觉得规则为了兼容性还是得加上，也不影响firefox

**Comment by dupontjoy** [comment]
哦, Chrome系不行的话, 问下作者@sylingd

**Comment by sylingd** [comment]
规则问题，请求头不要留空，改成`http://www.126.net`就行了

**Comment by dupontjoy** [comment]
因为同样的规则Firefox能生效, Chrome不行, 所以我想能不能从扩展层面解决
不行的话那就只有改规则了

**Comment by sylingd** [comment]
我待会儿看看

**Comment by sylingd** [comment]
我抓包看了一下，准确的说应该是Firefox的BUG
这是在Chrome下的抓包
![qq 20171116202813](https://user-images.githubusercontent.com/5326684/32891571-fc1cae12-cb0d-11e7-974f-33efa092c5ef.png)
这是Firefox下的抓包
![qq 20171116202902](https://user-images.githubusercontent.com/5326684/32891503-b70d6e42-cb0d-11e7-875e-ca046d900fd5.png)
可以看到Chrome是正常的Referer为空，Firefox却直接把它删掉了
126应该允许无Referer，但是不允许空Referer
