### ISSUE TITLE
请教怎么添加到header editor

### ISSUE THREAD

**Issue by jorismq** [dupontjoy/customization#17]
我下载了josn文件，点“导入”没用
网址填了https://github.com/dupontjoy/customization/blob/master/Rules/HeaderEditor/headereditor-all.json，点“下载”也没有

**Comment by dupontjoy** [comment]
网址要填raw那个
或者点击raw再另存为文件, 再导入

**Comment by zanewayne78** [comment]
raw打开502: Failure，这是被github屏蔽下载了吗
