### ISSUE TITLE
HE:inoreader全站反盗链的js写错了

### ISSUE THREAD

**Issue by lengthmin** [dupontjoy/customization#19]
![image](https://user-images.githubusercontent.com/13938334/44985952-cd693b80-afb4-11e8-890a-03331c4b85ea.png)

之前写了一篇文章讲chrome利用he来实现inoreader反盗链阅读, 留的地址是本项目..
结果有人反映并不行, 要改成图中这样
```
for (let a in val) {
	if (val[a].name.toLowerCase() === 'referer') {
                if (val[a].value.includes('inoreader.')) {
		     val.splice(a,1);
		     break;
	        }
	}
}
```

**Comment by dupontjoy** [comment]
好的,我都没用上,从网友那收集来的
