### ISSUE TITLE
如果不加速直接使用SS, iptables里面需要开放Shadowsocks服务端的端口吗？

### ISSUE THREAD

**Issue by kang000feng** [dupontjoy/customization#2]
你好，装了FS后，用iptables -L查看到只有FS的规则，如果关闭FS服务直接使用SS, iptables里面需要开放Shadowsocks服务端的端口吗？
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
DROP       tcp  --  anywhere             anywhere             tcp dpt:150 /* tcp                              tun_fs_server */
ACCEPT     udp  --  anywhere             anywhere             udp dpt:150 /* udp                              tun_fs_server */

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

**Comment by dupontjoy** [comment]
FS免费版并不是很稳定,我是原版SS跟FS加速流量均衡来用的,这样的话看视频时稍慢,但是能保证正常浏览网页.
教程里那个端口设置我没有弄



dupontjoy@163.com
 
发件人： kang000feng
发送时间： 2016-05-30 16:41
收件人： dupontjoy/customization
主题： [dupontjoy/customization] 如果不加速直接使用SS, iptables里面需要开放Shadowsocks服务端的端口吗？ (#2)
你好，装了FS后，用iptables -L查看到只有FS的规则，如果关闭FS服务直接使用SS, iptables里面需要开放Shadowsocks服务端的端口吗？
Chain INPUT (policy ACCEPT)
target prot opt source destination
DROP tcp -- anywhere anywhere tcp dpt:150 /* tcp tun_fs_server /
ACCEPT udp -- anywhere anywhere udp dpt:150 / udp tun_fs_server */
Chain FORWARD (policy ACCEPT)
target prot opt source destination
Chain OUTPUT (policy ACCEPT)
target prot opt source destination
