### ISSUE TITLE
[建议] 将 ghacks 的 user.js 文件压缩包替换为链接

### ISSUE THREAD

**Issue by Crystal-RainSlide** [dupontjoy/customization#21]
鉴于 ghacks user.js 项目已经迁移至 GitHub，建议将 [Firefox/user.js-ghacks-0.08.zip](https://github.com/dupontjoy/customization/blob/master/Firefox/user.js-ghacks-0.08.zip) 删除，并在 [Firefox/readme.md](https://github.com/dupontjoy/customization/blob/master/Firefox/readme.md) 中添加其链接： https://github.com/ghacksuserjs/ghacks-user.js

<del>这样一来就用不着更新这个文件了</del>

**Comment by dupontjoy** [comment]
好的, 好早以前传的, 放着也没管
现在Firefox定制性差多了, 基本都各玩各的了
