### ISSUE TITLE
怎么订阅 headereditor.json 更新？

### ISSUE THREAD

**Issue by sgrjyb** [dupontjoy/customization#3]

**Comment by ivysrono** [comment]
https://github.com/FirefoxBar/HeaderEditor/issues/9
说服作者加入订阅功能

**Comment by dupontjoy** [comment]
我不需要订阅, 只希望配置文件保存位置能换到extension-data下面

**Comment by ivysrono** [comment]
如果有多台设备要同步，就迫切需要订阅功能了。

**Comment by sgrjyb** [comment]
@dupontjoy  Redirector.json适用chrome吗？

**Comment by dupontjoy** [comment]
@ivysrono 其实像xstyle那样可以同步到Googlecloud也不错

**Comment by ivysrono** [comment]
WebDAV最好

**Comment by sylingd** [comment]
已经增加直接在管理界面下载并安装规则的功能~

**Comment by sgrjyb** [comment]
@sylingd  云同步 有计划吗？

**Comment by sylingd** [comment]
云同步暂时还没想好
