### ISSUE TITLE
headereditor.json  你是直接在headereditor中编辑然后导出吗？或者说用什么Windows软件打开headereditor.json不会乱码？谢谢

### ISSUE THREAD

**Issue by sgrjyb** [dupontjoy/customization#4]

**Comment by dupontjoy** [comment]
我是在扩展设置里一个一个添加的规则, 然后导出的
导出的json格式很糟糕, 有人向作者反馈了, 但是作者觉得没必要改, 受不了哈哈

当然, 也可以自己在线json美化一下格式: http://tool.oschina.net/codeformat/json

**Comment by sgrjyb** [comment]
能不能移植 https://github.com/ivysrono/URLRedirectorRules/blob/master/Directly.json 规则到 Header Editor ？哈

**Comment by sgrjyb** [comment]
还有 headereditor.json 没有跳转规则 能不能增加？

**Comment by dupontjoy** [comment]
重定向规则都是可以改的, 照着格式, 懂一点基础的正則就行了
我的规则里只加了我平时常用到的重定向规则

**Comment by sgrjyb** [comment]
呜呜

**Comment by sgrjyb** [comment]
Javascript-css beautify 怎么用？

**Comment by sgrjyb** [comment]
Javascript-css beautify 不支持chrome？

**Comment by dupontjoy** [comment]
应该支持的用TamperMonkey加载

**Comment by sgrjyb** [comment]
是直接把 headereditor.json 拖进chrome，还是怎么用？
