### ISSUE TITLE
qq图片盗链挂了

### ISSUE THREAD

**Issue by sgrjyb** [dupontjoy/customization#5]
https://imgcache.qq.com/qzone/client/photo/swf/no.gif

**Comment by dupontjoy** [comment]
请发图片原始地址

**Comment by sgrjyb** [comment]
这看到的 http://bbs.kafan.cn/thread-2102542-1-1.html

**Comment by dupontjoy** [comment]
我这里全部图片都能显示

**Comment by dupontjoy** [comment]
那就不知道了
