### ISSUE TITLE
CHH防盗链规则会导致登录验证码不显示

### ISSUE THREAD

**Issue by liangxyz** [dupontjoy/customization#8]
如题，测试环境：百分浏览器2.8+head editer

**Comment by dupontjoy** [comment]
具体是哪一条规则, 我好改一下

**Comment by sevilx** [comment]
chiphell图片盗链，.*\.chiphell\.com.*  这条规则，正好我也想反馈这个，我现在是把这规则关了就显示验证码了

**Comment by dupontjoy** [comment]
![3](https://user-images.githubusercontent.com/4965288/32205388-f22f30c8-be29-11e7-9db0-afa74bb1de9a.jpg)
这个验证码? 可以显示的样子

**Comment by sevilx** [comment]
对，就是这个验证码，但是我把规则打开了，怎么也显示不了。关了就能显示，我开始以为是其他插件的问题，一个一个排查发现是这个规则的问题。

**Comment by sevilx** [comment]
![_20171031110952](https://user-images.githubusercontent.com/18444005/32205803-6369df16-be2c-11e7-8326-08cd2cf67453.png)
![_20171031110936](https://user-images.githubusercontent.com/18444005/32205804-63d1d832-be2c-11e7-836b-3a202b694347.png)

**Comment by dupontjoy** [comment]
`^https?:\/\/www\.chiphell\.com\/.*`
这样呢?

**Comment by dupontjoy** [comment]
规则都写的比较宽泛, 实在有问题再考虑把适用范围缩小

**Comment by sevilx** [comment]
改了之后可以显示了，谢谢！
