### ISSUE TITLE
HeaderEditor使Nightly58中卡住的原因可能找到了

### ISSUE THREAD

**Issue by sylingd** [dupontjoy/customization#9]
我测试了一下，卡住的原因应该是以`(.*)`、`(.+)`这一类"通配符"开头的正则，不知道因为什么BUG就会卡住Firefox。
但是单独在console里执行这一类正则表达式则不会
暂不清楚具体原因
建议将此类规则的"通配符"暂时移除掉

**Comment by dupontjoy** [comment]
`以(.*)、(.+)这一类"通配符"开头的正则`
是指这种么?
![13](https://user-images.githubusercontent.com/4965288/31430359-35885ee4-aea3-11e7-94c7-be36e54c4433.jpg)
如果(.*), (.+)不在开头, 就没事么?

**Comment by sylingd** [comment]
这两条似乎不会导致卡住的问题。我测试的时候，把`(.`开头的规则禁止掉就没问题了

**Comment by dupontjoy** [comment]
好的, 我改下规则, 这下又可以开心的用Nightly了
